### ISSUE TITLE
Post Edits

### ISSUE THREAD

**Issue by dansup** [pixelfed/pixelfed#3215]
Issue to track the **Post Edits** feature - the ability to edit your posts. 
At the moment we are only targeting **Mastodon** compatibility and our rough ETA is **June 2022**.

### Todo
- [x] Frontend UI
   - [ ] Edit link in menus
   - [ ] Edit form
   - [ ] Edit error messages
- [x] Backend
   - [ ] Handle media updates (S3, filters, blurhash, thumbnails, storage used, order)
   - [ ] Store history (new one-to-many relationship)
   - [ ] Cache invalidation
   - [ ] Rate limit
- [x] API
   - [ ] Web + Masto endpoints
   - [ ] Realtime updates
- [x] ActivityPub Federation
- [ ] Unit Tests
- [ ] Documentation (ActivityPub & API)
- [ ] Compatibility Tests
- [ ] Opt-in beta rollout & testing
- [x] Community
   - [ ] Announce feature
   - [ ] Update relevant issues

### Compatibility
- Mastodon ([issue](https://github.com/mastodon/mastodon/pull/16697))

### Notes
We're testing a new process for this feature, this issue will act as our roadmap and track development progress.

**Comment by mitexleo** [comment]
This is the most important feature I want at this moment. 
Because I'm pretty bad at writing captions and always make mistakes :)

**Comment by dansup** [comment]
Shipped in #4416
