### ISSUE TITLE
Implement Mastodon-only registration/login 

### ISSUE THREAD

**Issue by colega** [pixelfed/pixelfed#5160]
## Description of the feature

I want to run Pixelfed for my Mastodon instance users: I want them to share same handlers, and I want to completely disable all kinds of email registration.

# Tasks

So far I've identified the following tasks:

- [ ] Disable email login form
  - This would be a new configuration.
  - If set, the login controller should redirect to mastodon login, (if enabled).
- [ ] Force usage of the Mastodon handler as username in Mastodon sign-in process
  - Also a new setting, should look like this: 
![image](https://github.com/pixelfed/pixelfed/assets/1511481/97c6b4bb-646f-4729-919d-4bbfea2ad52b)
  - If username is not available, user shouldn't be able to continue with the registration.
- [ ] Skip mastodon server selection
  - One more configuration, only valid if there's only one custom server defined and only custom mastodon services are allowed.
  - If enabled, we'll skip the mastodon server selection screen, and redirect directly to our instance.

**Comment by colega** [comment]
These are very small changes, and I'm willing to contribute them.

**Comment by trendless** [comment]
have you had issues when importing the avatar? Can you change it after import from within pixelfed?
