### ISSUE TITLE
[Masterpost] Missing functionality and related issues from the beta launch

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#73]
Figured it'd be good to maintain a list of things that are currently missing and would be expected to be implemented.

## Timeline/posts
Posts
- [x] ~Posting UI should be separated from timeline (#89, #86 #168, fixed #349 )~
- [x] ~Post without a caption (#110)~
- [x] ~Show caption limit before posting (#121, fixed by #127)~
- [x] ~Show size/format limit before posting~
- [ ] Preserve caption for editing if too long (#236)
- [x] ~Show live character count for JS users (#346)~
- [x] ~Preview image before posting (#171)~
- [x] ~Preview multiple images before posting (https://github.com/dansup/pixelfed/issues/171#issuecomment-397224719, fixed by #524 )~
- [x] ~Delete images (#98)~
- [x] ~Show own posts in personal timeline (#85) (fixed by #190)~
- [x] ~Filters~
- [x] ~Separate filters for each image in album (#266, fixed in #524)~
- [x] ~Edit filters after upload (#798)~
- [ ] Edit album order (#798)
- [ ] Embed code (currently #) (#776)

Likes
- [x] ~Indicate liked posts with filled heart rather than underline (#70) (fixed #186 #187 #188)~
- [x] ~Indicate liked posts on post page, not just on timeline (#207)~
- [ ] Animation for liking a post (potentially fixed by #222)
- [x] ~Storing liked/unliked state without having to refresh the page (#87) (fixed by #186)~
- [x] ~Listing who liked a post (#213)~

Comments
- [x] ~Comment button should link to all comments (#161)~
- [x] ~Load more comments~
- [x] ~Parse mentions (#231)~
- [x] ~Parse hashtags~
- [x] ~Parse links~
- [x] ~Like comments~
- [x] ~Reply to comments~
- [x] ~Delete comments (#97)~
- [x] ~Show comment in context on permalink (#234)~
- [ ] Show live character count for JS users
- [ ] Preserve comment for editing if too long (WIP #236)

Save
- [x] ~Saving posts not implemented fully -- can't unsave posts (#64)~

## Search/tags:
- [x] ~Hashtag suggestion breaks with 3+ characters or # sign (#76, fixed by #488)~
- [ ] Sort tag suggestions by how many posts they have
- [x] ~Irregular suggestions (#88)~
- [x] ~Hashtag page avatars (#69)~

## Discover:
- [x] ~Scroll through profile suggestions, show more than just 3 at a time (deprecated)~
- [x] ~Allow for temporarily / permanently clearing a suggestion (deprecated)~
- [x] ~Do not clear suggestion immediately after following (only clear on page refresh, to allow undo) (deprecated)~
- [x] ~Do not suggest your own account (#74) (fixed by #108) (deprecated)~
- [x] ~Uniform square thumbnails (potentially fixed by #168)~

## Activity:
- [x] ~"Follow" button should change after following someone (#63) (fixed by #95)~
- [x] ~Notifications of liked posts should link to those posts (#58)~
- [ ] New notification indicator

## Profile:
- [x] ~Count only images as "posts" (#84) (fixed by https://github.com/dansup/pixelfed/commit/ae6a59e782713bfd73924dbf271e646fe00bc656)~
- [x] ~Follower/following lists should allow un/following accounts (#65) (fixed by #105)~
- [x] ~Detect and regenerate failed thumbnails (#67)~
- [x] ~Unsave posts from "Saved" tab~
- [ ] Parse mentions in bio
- [ ] Parse hashtags in bio
- [ ] Parse links in bio
- [ ] Allow editing bio directly from My Profile
- [x] ~Show bio on follower/following pages~

## Settings:
- [x] ~Character count while setting bio (#59)~
- [x] ~Reduced motion (#226)~
- [ ] Finish user settings (#3)
- [x] ~Change avatar/email~
- [x] ~Email/notification/~privacy~/security settings~
- [ ] Import/export data (#814)
- [x] Applications/Developers OAuth

## Documentation:
- [x] ~"About" is sparse~
- [x] ~"Features" (removed)~
- [x] ~"Help" (some empty pages)~
- [ ] "Fediverse" is sparse
- [ ] "Open source" is sparse
- [x] ~"Terms"~
- [x] ~"Privacy" policy~
- [ ] "Platform"/API terms is orphaned https://pixelfed.social/site/platform
- [x] ~"Libraries" (removed)~

## Footer links:
- [x] ~"API" links to /timeline instead of api docs~
- [x] ~"Directory" (removed)~
- [x] ~"Profiles" (removed)~
- [x] ~"Hashtags" (removed)~
- [x] ~"Language" links nowhere~
- [x] ~"C 2018 PIXELFED.ORG" links nowhere (should link to pixelfed.org?)~
- [x] ~is copyright even the right symbol here? Shouldn't it instead reflect the license of the project somehow?~

Registration (#373):
- [ ] Terms
- [ ] Data policy
- [ ] Cookie policy

## Other things on the roadmap:
- "Major features" (#6)
  - [x] ~Image albums/video upload~
  - [ ] ~Mentions~/DMs

- [x] ~View public timeline while logged out (#214, replaced with Discover page)~

**Comment by trwnh** [comment]
I don't really want to add any separate bug reports here because this issue is targeted mostly at the stuff that stands out as missing when going through the UI and such. File separate issues for those, with much more details than a single line item!

**Comment by hellcp** [comment]
Relating to second point about hearting animation, we should consider simple solution of doing css animation, where small tear shaped things zoom in from behind the heart and fall down (something like confetti?).

It would also be nice to show that there are new notifications with a circle next to heart (is heart even the right symbol for notifications?, wouldn't bell make more sense?)

**Comment by trwnh** [comment]
@hellcp 

> we should consider simple solution of doing css animation, where small tear shaped things zoom in from behind the heart and fall down (something like confetti?)

Yeah, the animation itself would be easy, but no-JS users will see a bit of a hitch because the page has to refresh rather than on-the-fly applying the style. In the case of no-JS it's probably easier to not animate it (since the page refresh will count as an animation of sorts).

> It would also be nice to show that there are new notifications

I'll add that as a checkbox :)

> Is heart even the right symbol for notifications? Wouldn't a bell make more sense?

I'm guessing @dansup used a heart because Instagram uses a heart.

**Comment by mkljczk** [comment]
Isn’t it what [projects](https://github.com/dansup/pixelfed/projects/1) are for?

**Comment by trwnh** [comment]
@m4sk1n yeah, but i don't have write access, so dansup can convert this into a project when he wakes up

**Comment by mkljczk** [comment]
Could you mention my PRs for #63 and #65?

**Comment by mal0ki** [comment]
This is a beautiful post <3

**Comment by dansup** [comment]
@trwnh Thank you for making this! Its been hard to keep up with all the issue and PR's and I appreciate the work you and @kpcyrd are doing!

**Comment by ghost** [comment]
A small note on animations - A reduced motion feature where there are less animations or they're less flashy would be very very helpful. Figured we'd bring this up before it became a major issue, what with #222 already being in the works.

**Comment by trwnh** [comment]
@Fidgetcetera I feel that should be its own separate issue -- it has been referred to across some related issues, but should be its own feature request. I'll make an issue for it!

**Comment by mkljczk** [comment]
#121 is closed

**Comment by trwnh** [comment]
@dansup: per IRC

## Priority issues before federation:
- [x] ~Video support~
- [x] ~Post without a caption~
- [x] ~Delete/like/reply to comments~
- [x] ~Fix comment permalinks~
  - [x] ~wrong ID (https://github.com/dansup/pixelfed/issues/51#issuecomment-394677430)~
  - [x] ~wrong text (https://github.com/dansup/pixelfed/issues/312)~
  - [x] ~move likes counter next to comment (#234)~
  - [x] ~add buttons to perform like/reply/delete actions next to comment~
- [ ] Fix uri id vs. url distinction
  - [ ] Post `id` at /p/postid
  - [ ] User `id` at /u/userid
  - [ ] User `url` at /username or /@username
  - [ ] Post `url` at /username/postid or /@username/postid
- [x] ~Paginate / load more comments, sort oldest->newest~
- [x] ~Implement / parse mentions in captions and comments~
- [x] ~Set avatar~
- [ ] Notification settings
- [x] ~"Sensitive content" / content warning~
- [x] ~Content warning labels~
- [x] ~ActivityPub workers~

## Dependent issues / low hanging fruit:

- [x] ~"Reduced animation" setting~
  - [ ]  Animation for likes / etc
---
- [x] ~Mention handling~
  - [x] ~Mention parsing in~ bio~/captions/comments~
- [ ] Thread resolver
---
- [x] Live character counts for JS users
- [x] ~Indicate likes on post page, not just timeline~
- [x] ~Unsave posts~
- [ ] Parse links/hashtags in bio

**Comment by ghost** [comment]
Liking comments is supported as of v0.8.0

**Comment by trwnh** [comment]
Well, close to 16 months later and most of these line-items are outdated or have their own tracking issues :) so it's time to finally close #73!
